### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by FilipVlcek** [elementary/switchboard-plug-mouse-touchpad#105]
Hello. I have one issue with my touchpad. When I am using it normally speed of moving cursor is ok. But when I am trying to aim on a little thing and when I am working gently, then touchpad is moving like crazy...

**Comment by m93a** [comment]
You should provide more information about your hardware/drivers. Also have you tried the touchpad with a different OS to rule out hardware failure? I don't have any issues with my Acer A315's touchpad on elementary.

**Comment by m93a** [comment]
@danrabbit Close this?

**Comment by danrabbit** [comment]
Closing as "Out of Scope" since this sounds like a driver or libinput issue and there's nothing that can be done to resolve this within the scope of Mouse & Touchpad settings
