### ISSUE TITLE
Turn off issue

### ISSUE THREAD

**Issue by FilipVlcek** [elementary/switchboard-plug-mouse-touchpad#106]
When I am trying to turn off my computer, it is not working...

**Comment by tintou** [comment]
Unfortunately this bug isn't actionable, there is nothing we can do as you're not giving us any context. Please at least provide a screencast of your issue and describe your configuration.

**Comment by FilipVlcek** [comment]
Yes of course. If you need my config of my notebook then it is i5 8250U
with 8GB od ram and 256 GB SSD.
And this problem is happening sometimes. 1 out of 7 times maybe. If you
need to see what is happening then next time it will happend I will record
it or do something like that. Have a nice day

Dňa ut, 5. nov 2019, 12:31 Corentin Noël <notifications@github.com>
napísal(a):

**Comment by tintou** [comment]
Alright, no problem, please reopen this issue when you're able to reproduce it on your end
