### ISSUE TITLE
Touchpad on dell XPS13-9333

### ISSUE THREAD

**Issue by Antux-91** [elementary/switchboard-plug-mouse-touchpad#117]
After the last update to Hera, the touchpad has stopped to work.

**Comment by danrabbit** [comment]
Touchpad drivers are controlled upstream in the Ubuntu kernel. Please report any driver issues in the Ubuntu kernel bug tracker in Launchpad

Closing as "out of scope" since this issue can't be resolved in the scope of mouse and touchpad settings
