### ISSUE TITLE
Macbook Pro 13in w/Touchbar (2017)

### ISSUE THREAD

**Issue by Macro99** [elementary/switchboard-plug-mouse-touchpad#118]
None of the following work elementary OS 5.1 Hera after installing: keyboard, touchpad, touchbar speakers, camera, and possibly microphone. Again this is using a Macbook Pro 13in w/Touchbar (2017).

**Comment by kgrubb** [comment]
The macbook pro 2017 has some known issues with linux support in general. Fortunately, there are some community efforts to document and resolve these issues. 

Here's some good information on hardware/software support for macbook pros from 2016-2017: https://github.com/Dunedan/mbp-2016-linux
