### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by EOSfranklin** [elementary/switchboard-plug-mouse-touchpad#121]
Meu notebook é um Dell Inspiron core i3 de sexta geração. Após instalar o Elementary OS 5.1 Hera o Touchpad do notebook parou de funcionar! Funcionando apenas no Mouse comum.
Ressalto que no Elementary OS 5.0 Juno, estava tudo funcionando normalmente. 

Além desse problema, a central de apps do Elementary OS 5.1 HERA, esta com problemas ao buscar os repositórios, dando falha ao buscar por atualizações. Esse problema tem sido recorrente nas versões do sistema, mesmo tendo sido instalado várias vezes o OS.

**Comment by danrabbit** [comment]
Closing as a duplicate of #117
