### ISSUE TITLE
Switches are stretched on HiDPI with no scaling and large font

### ISSUE THREAD

**Issue by Alecaddd** [elementary/switchboard-plug-mouse-touchpad#132]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The Switches used in the new Mouse and Touchpad panels appear stretched.
I'm using a HiDPI monitor 3840x2160, with no scaling and Larger Text Size.

### To Reproduce
1. Go to System Settings
2. Click on Mouse & Touchpad

### Expected behavior
The switches should be centred aligned and not stretched.
I think a simple `valign = Gtk.Align.CENTER` might do the trick.

### Screenshots or screen recordings
![Screenshot from 2020-01-21 16-29-33](https://user-images.githubusercontent.com/2527103/72855299-d58a4f80-3c6b-11ea-8951-78462eebe63a.png)

## Platform Information
![Screenshot from 2020-01-21 16-35-30](https://user-images.githubusercontent.com/2527103/72855358-0e2a2900-3c6c-11ea-90a9-76e5b94f227a.png)

- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment]
It looks like this has already been fixed. I can't reproduce the issue in elementary OS 6 daily
