### ISSUE TITLE
Problem with integrated touchpad

### ISSUE THREAD

**Issue by ScioZioDave** [elementary/switchboard-plug-mouse-touchpad#136]
I've a problem with my touchpad, in all linux system doesn't work anymore, I tried in Windows OS and it still work.

How can I fix this problem?

**Comment by mvandermade** [comment]
I'm not sure I can help you with the installation. 

But I can help you start troubleshooting...

The input device should be listed in the following file:
```
/proc/bus/input/devices
```

Or try if anything is detected at all that looks like a touchpad:
https://www.binarytides.com/linux-commands-hardware-info/

Would be nice if the tooling would be able to detect this (if no mouse is attached at all, and the device should be a laptop that is). How did you solve the problem?

**Comment by danrabbit** [comment]
Touchpad drivers are controlled upstream in the Ubuntu kernel. Please report an issue in the upstream Ubuntu kernel issue tracker in Launchpad

Closing as "Out of scope" since driver issues cannot be resolved in mouse and touchpad settings
