### ISSUE TITLE
Touchpad 3 finger tab on links opens 2 tabs on browser

### ISSUE THREAD

**Issue by VenomIND** [elementary/switchboard-plug-mouse-touchpad#139]
## Platform Information
 - OS: elementary OS
 - OS Version : 5.1.3
 - Hardware info: Dual-Core Intel® Core™ i3-7100U CPU @ 2.40GHz
                            Intel Corporation HD Graphics 620 (rev 02)
                            8.1 GB memory
                            115.6 GB storage (SATA SSD)
  - Device Model- HP 15-da0326tu

Please check what applies:
-->
- [x] I have not changed anything into the system just installed chrome & firefox and both have same issue.. The touchpad was just working fine on Ubunut and Manjaro.
- [ ] I'm using the latest released stable version 5.1.3 (Clean Installed on 08/04/2020)

Thank you.. I'm waiting for your reply.

**Comment by VenomIND** [comment]
## Platform Information
 - OS: elementary OS
 - OS Version : 5.1.3
 - Hardware info: Dual-Core Intel® Core™ i3-7100U CPU @ 2.40GHz
                            Intel Corporation HD Graphics 620 (rev 02)
                            8.1 GB memory
                            115.6 GB storage (SATA SSD)
  - Device Model- HP 15-da0326tu

Please check what applies:
-->
- [ ] I have not changed anything into the system just installed chrome & firefox and both have same issue.. The touchpad was just working fine on Ubunut and Manjaro.
- [ ] I'm using the latest released stable version 5.1.3 (Clean Installed on 08/04/2020)

Thank you.. I'm waiting for your reply.

**Comment by cassidyjames** [comment]
This is almost certainly down to touchpad drivers; we're not doing anything special or different here from Ubuntu or GNOME. This codebase just hooks into the exact same underlying settings as GNOME or Ubuntu would.

**Comment by VenomIND** [comment]
No it's specific to elementary latest build only .. I have installed Ubuntu 18.04.4 and Ubuntu 20.04 beta and Pop os all of them using same drivers etc and my touchpad works perfectly without any problem... So if everything is the same in Ubuntu and elementary then what's the issue? I guess there might be a but in the latest build of elementary that creating the issue that 3 finger click ( midle click in the mouse) opening duplicate tab (2Tabs) I have also tested this with my Logitech M235 wireless mouse.. middle click also opens 2 tabs .. but it's about 2/10 times but in touched it's about 6/10 times .. this is really annoying..

**Comment by VenomIND** [comment]
> This is almost certainly down to touchpad drivers; we're not doing anything special or different here from Ubuntu or GNOME. This codebase just hooks into the exact same underlying settings as GNOME or Ubuntu would.

No it's specific to elementary latest build only .. I have installed Ubuntu 18.04.4 and Ubuntu 20.04 beta and Pop os all of them using same drivers etc and my touchpad works perfectly without any problem... So if everything is the same in Ubuntu and elementary then what's the issue? I guess there might be a but in the latest build of elementary that creating the issue that 3 finger click ( midle click in the mouse) opening duplicate tab (2Tabs) I have also tested this with my Logitech M235 wireless mouse.. middle click also opens 2 tabs .. but it's about 2/10 times but in touched it's about 6/10 times .. this is really annoying..
