### ISSUE TITLE
Option to activate/deactivate two finger right click

### ISSUE THREAD

**Issue by mvandermade** [elementary/switchboard-plug-mouse-touchpad#143]
## Prerequisites
- [ x ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

I'm always annoyed when i'm reading a pdf and accidentally tap with 2 fingers on the touchpad. This then pops up the right click menu, which I was not expecting... Then I was frustrated when I was not able to easily adjust this behaviour. I could disable "tap to click" all together, but that is annoying too.

![Schermafdruk van 2020-04-18 12 19 09](https://user-images.githubusercontent.com/33425497/79635079-fc72f780-816e-11ea-8cae-fa9a0d091bbb.png)

The settings menu:
![Schermafdruk van 2020-04-18 12 21 53](https://user-images.githubusercontent.com/33425497/79635107-3e03a280-816f-11ea-8233-38f0c747520f.png)

**Describe the solution you'd like**

The solution I would like is the feature described here at 5.)
https://support.apple.com/guide/bootcamp-control-panel/set-trackpad-options-bcmpa82153f3/mac

"""
Under Two Fingers, select Secondary Click to be able to perform a secondary click by placing two fingers on the trackpad, then clicking.
"""

**Existing work**

Elsewhere I have seen it on many other software platforms.
Most commonly the option is displayed in the "mouse" or touchpad settings.
Most commonly this feature is by default turned on.

**Describe alternatives you've considered**

I considered installing a third party tool to fix it (but didn't yet).

**Additional context**

**Comment by danrabbit** [comment]
In order to implement this, we would need this option to be exposed in GNOME Settings Daemon. Please report an issue upstream in GitLab: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues

Closing as "Out of scope" since this is just a frontend to the settings provided by GNOME Settings Daemon and the requested option isn't available upstream
