### ISSUE TITLE
Reveal pointer schema doesn't exist in focal

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-mouse-touchpad#146]
I think GNOME has moved this to be implemented inside of GNOME Shell, so the previous schema doesn't exist—and our setting disappears from the pane.

**Comment by danrabbit** [comment]
Also see https://github.com/elementary/gala/issues/715

**Comment by cassidyjames** [comment]
Aha, thanks. I thought I recalled this already being filed and was surprised when I couldn't find it. :smile:
