### ISSUE TITLE
need hep with my laptop

### ISSUE THREAD

**Issue by jilws** [elementary/switchboard-plug-mouse-touchpad#163]
hi good day i have a laptop model epson endeavor NJ3900e with touchpad driver problem hope you can help me with this concern

**Comment by danrabbit** [comment]
Touchpad drivers are managed as part of the upstream Ubuntu kernel, so any issues should be reported in the Ubuntu kernel bug tracker in Launchpad.

Closing as "Out of scope" since this issue cannot be resolved within the scope of mouse and touchpad settings here
