### ISSUE TITLE
the secondary click of the touchpad does not work well

### ISSUE THREAD

**Issue by Idan-A** [elementary/switchboard-plug-mouse-touchpad#180]
I tried elementary os 6 on my acer and the touchpad when I wanted to make secondary clicks with the right side, it "read" them as primary

**Comment by cassidyjames** [comment]
The default is multi-touch. Did you change the setting in **System Settings** > **Mouse & Touchpad** > **Touchpad** > **Physical secondary clicking** to "Areas"? If so, the area will be the bottom-right side of the touchpad when physically clicked down. Tap-to-click is always a primary click.

**Comment by lenemter** [comment]
Closint because no more information provided.
