### ISSUE TITLE
More Click Settings Options

### ISSUE THREAD

**Issue by 4turtlez** [elementary/switchboard-plug-mouse-touchpad#181]
The hybrid and dwell clicks are interesting options for the click and i am sure useful to many. But it would be nice to have the option to pick just single or double click as well in settings.

**Comment by 4turtlez** [comment]
I was meaning single and double click options would be great to have in addition to the others in settings for opening folders/files in Files manager.

Sorry about messing up posting

**Comment by jeremypw** [comment]
It was a conscious design decision to drop support for multiple click modes in Files in favour of a single more easily supported mode. lnevitably a number of users will have to get used to the new mode.  The form of the cursor when hovering the icon tells the user what will happen on clicking although design improvements are probably possible in making it obvious that the folder icons are more like hyperlinks than file objects.
