### ISSUE TITLE
Tap-and-drag toggle

### ISSUE THREAD

**Issue by YoKoGFX** [elementary/switchboard-plug-mouse-touchpad#184]
It would be great if the OS would have a system level (GUI) option to disable double-tap to select while keeping the single tap to click. This is described in this askubuntu posting.

https://askubuntu.com/a/1115136

**Comment by cassidyjames** [comment]
@YoKoGFX to clarify, the AskUbuntu post you link to mentions the tap-and-drag feature, e.g. when you quickly double-tap the trackpad and then move your finger to drag things things like a window or to select free-form text. This feature is available to us, and I think it would make sense to add a setting for the accessibility and hardware compatibility implications. 

However, regardless of this setting, it seems that double-tapping a word selects it. If that's the functionality you're looking to disable, I think it would be lower-level, e.g. possibly in GTK itself.
