### ISSUE TITLE
3 & 4 finger swipe options to move the active window into the previous/next workspace respectively

### ISSUE THREAD

**Issue by Schykle** [elementary/switchboard-plug-mouse-touchpad#186]
## Problem

Currently there are settings that allow three or four finger swipes horizontally to move into adjacent workspaces. However, there are no options that will slide the active window into an adjacent workspace.

## Proposal

If possible, a gesture option that allows setting three or four finger swipe to move the active/selected window into an adjacent workspace. This would be reflective of the `Super`+`Alt`+`Arrow` shortcut as the current settings can be reflective of the `Super`+`Arrow` shortcut.

## Prior Art
I'm not actually sure how gestures in elementary OS are executed so please excuse my ignorance, though in the past I've manually enabled gestures via tools like Gestures, xdotool, and libinput-gestures to call keyboard shortcuts for window and workspace management with touchpad gestures. I'm not sure of the complexity of implementing this, but I thought I would bring it up!

Thanks!

**Comment by cassidyjames** [comment]
Thanks for the issue report! I think this would be implemented first in Gala (and possibly touchégg before that), but I'll leave this issue here for now as they're all interconnected. 

cc @elementary/ux and @JoseExposito for input, though.

**Comment by JoseExposito** [comment]
There is a similar issue opened in Gala: https://github.com/elementary/gala/issues/1109

As I mentioned, this is possible at the moment, but difficult/impossible to perform depending on hardware, plus, the animation is broken.

I think that using a shortcut is the best option. Only changes in Gala would be required.

**Comment by janxkoci** [comment]
Idea:

- 3 fingers = change workspace (~`Super+Arrow`)
- 4 fingers = move window while changing workspace (~`Super+Alt+Arrow`)

**Comment by lenemter** [comment]
Closing in favour of https://github.com/elementary/gala/issues/1109
