### ISSUE TITLE
Some settings don't work with synaptics driver

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-mouse-touchpad#19]
I think due to a recent LibInput update, the settings under "Physical clicking" (which use `org.gnome.desktop.peripherals.touchpad`) no longer change anything; it appears physical clicking is forced to be on, and forced to use the hardware defaults.

Ideally, we could figure out what broke between LibInput and the GNOME keys, or perhaps there are new keys we're supposed to use that are respected. Barring that, we should at least remove the settings for now since broken settings are worse than no settings at all. :(

**Comment by danrabbit** [comment]
I can't confirm that this is the case in Juno (everything works as expected), so there must be some problem with the versions of various components in Loki specifically.

**Comment by cassidyjames** [comment]
@danrabbit that's a relief, at least :sweat_smile: 

There was recently a LibInput change in Loki that appears to have improved some things (scrolling, especially), but broke some integration with the GNOME GSettings. Given that, I think we should _probably_ remove those settings in Loki unless it's easy enough to fix whatever broke.

**Comment by cassidyjames** [comment]
Removing `xserver-xorg-input-synaptics-hwe-16.04` made the settings work again, but now cursor movement is super slow and seemingly more jumpy, and scrolling inertia is pretty janky.

**Comment by png2378** [comment]
This is not relevant to this issue, but I and some other users have problems after latest libinput update – touchpad cursor movement less smooth and more slow than it used to be. [[1]](https://www.reddit.com/r/elementaryos/comments/6qo2pw/touchpad_pointer_got_really_sloooww/) [[2]](https://bugs.launchpad.net/elementaryos/+bug/1707032)

I'm not happy with such significant changes on stable release. The only solution that I found is [downgrade graphical stack](https://elementaryos.stackexchange.com/a/12948/160) (remove HWE support).

**Comment by danrabbit** [comment]
It seems like the only real option as far as the plug is concerned is to detect the presence of the synaptics driver and not show those settings if it is in use

**Comment by danrabbit** [comment]
@cassidyjames have you tried to reproduce these issues lately? Do we care that much if someone manually changes their kernel?

**Comment by cassidyjames** [comment]
@danrabbit yeah I don't think this is an issue anymore—we can close this and always revisit if it comes up again.
