### ISSUE TITLE
Touchpad is not detected at all

### ISSUE THREAD

**Issue by arch3rtemp** [elementary/switchboard-plug-mouse-touchpad#192]
### What Happened?

After migrating to Linux (Odin) from Windows 10, I discovered that touchpad does not work on my Lenovo V15-IIL. It has Synaptics touchpad.
I think the issue is with the libinput library. 
I have installed:

- libinput
- evdev
- mouse
- synaptics

nothing works. _xinput_ does not detect any touchpad. I tried adding in grubloader _i8042.reset i8042.nomux i8042.nopnp i8042.noloop_ but to no avail.

I think it is a major bug in linux kernel. Do not know what to think else.
Can you help?

### Steps to Reproduce

Try running elementary os 6 on laptops with Synaptics touchpad

### Expected Behavior

It just cannot detect Synaptics touchpad

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by arch3rtemp** [comment]
I guess I have to create another thread on Lenovo support site :)

**Comment by danrabbit** [comment]
Gonna close this since it sounds like an issue with firmware and not an issue with elementary OS

**Comment by Oriel-Barroso** [comment]
The solution of the grub dont work on ubuntu 22.04 and the os dont start, this solution brokes the grub, and if delete 'pci=nocrs' the system start fine
