### ISSUE TITLE
Pinch to zoom with 2 fingers for zoom in/out isn´t working

### ISSUE THREAD

**Issue by Izval** [elementary/switchboard-plug-mouse-touchpad#223]
### What Happened?

It works with 3 even 4 fingers but the basic 2 fingers don´t and I use the touchscreen to make it something unnatural and that not many devices have and causes inconsistencies or the mouse to hide, can you solve it?

### Steps to Reproduce

Pinch to zoom in a website like figma with the trackpad, if you have a touchscreen and you use it the mouse hides 

### Expected Behavior

Zoom in or zoom out when pinch with two fingers on the trackpad and a visible mouse

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Thinkpad T480, i78650U, Nvidia MX150, 16 gb ram, 256 ssd
elementary OS 7.1 Horus

**Comment by danirabbit** [comment]
Two finger pinch to zoom is working here with Web on OS 8 in the Wayland session, so I'm going to close this as "Fixed"

**Comment by thesupertechie** [comment]
@danirabbit Hmm...this isn't working on OS 8.1 in Wayland, it instead switches desktops...

**Comment by thesupertechie** [comment]
To clarify, pinching with two fingers switches desktops, unlike every other desktop I've used, which uses two-finger pinch to zoom in. This is especially problematic for me.
