### ISSUE TITLE
The new Mouse Pointer icons. Elementary OS 8.0

### ISSUE THREAD

**Issue by myhousece** [elementary/switchboard-plug-mouse-touchpad#240]
### Problem

In my opinion, they are simply fantastic, a very beautiful design! Another little piece to fit in with the perfection that Elementary OS is becoming in the Linux world!

### Proposal

So I just came to praise the excellent work of those who produced them. Congratulations!

I apologize for using this space to make this compliment, but I needed to express my happiness and gratitude to those who are always dedicating themselves to good causes. Congratulations indeed!
![friendly](https://github.com/user-attachments/assets/393e2f56-c5d7-4045-b008-4d5c5acd389a)

**Comment by danirabbit** [comment]
Aww thank you very much! It's always nice to get positive feedback. Really glad you like them 😊

Closing since there's nothing actionable here haha. Thanks again 🩷
