### ISSUE TITLE
meson build shows a warning

### ISSUE THREAD

**Issue by coolpolygons** [elementary/switchboard-plug-mouse-touchpad#33]
Version: 0.45.0
Source dir: /home/jacob/switchboard-plug-mouse-touchpad
Build dir: /home/jacob/switchboard-plug-mouse-touchpad/build
Build type: native build
Project name: mouse-touchpad
Native C compiler: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609")
Native Vala compiler: valac (valac 0.36.13)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency switchboard-2.0 found: YES 2.0
Native dependency glib-2.0 found: YES 2.48.2
Native dependency gio-2.0 found: YES 2.48.2
Native dependency gobject-2.0 found: YES 2.48.2
Native dependency granite found: YES 0.5
Native dependency gtk+-3.0 found: YES 3.18.9
WARNING: pkgconfig variable 'plugsdir' not defined for dependency switchboard-2.0.
Build targets in project: 4
Found ninja-1.8.2 at /usr/bin/ninja

I tried editing a code in the widgets section, "TouchpadSection.vala" . When i tried running meson build --prefix/usr , it shows me the warning that plugsdir is not defined for dependency switchboard-2.0. Is this supposed to happen?

**Comment by tintou** [comment]
You need the next version of libswitchboard which will come with elementary Juno

**Comment by coolpolygons** [comment]
how do i install that? cuz right now, sudo ninja install is installing in /usr/hardware ...

**Comment by tintou** [comment]
https://github.com/elementary/switchboard
