### ISSUE TITLE
touchpad-indicator cannot work

### ISSUE THREAD

**Issue by ad735** [elementary/switchboard-plug-mouse-touchpad#43]
my  computer is dell-Inspiron-5557,it works with elementary os juno,but i cannot close the touchpad,so i need the help by touchpad-indicator.the touchpad-indicator works wll in elementary os freya,but in the juno, it just cannot work.when i run it,it will not appear in the wingpanel,when dissappear,no any response.it is important for me,please help me.

**Comment by peteruithoven** [comment]
Could you please clarify:
- "i cannot close the touchpad". How would you "close" the touchpad device. Do you mean disable?
- "touchpad-indicator". There is no touchpad indicator?

**Comment by ad735** [comment]
in freya,I disable the touchpad with toupad-indicator(it is a app work with the linux),but in juno,it cannot work again.in freya,I can find lots of indicator when I run app,but in juno,the indicator has bug,they never find in the winglepanel

**Comment by peteruithoven** [comment]
Was that a elementary OS specific app? Do you have a link? It could be that this was an ayatana indicator, this isn't something Juno supports anymore.

**Comment by ryonakano** [comment]
I think this is that: https://github.com/atareao/Touchpad-Indicator

**Comment by danrabbit** [comment]
I'm going to close this issue report as "Out of Scope" since this problem can't be solved in the scope of this page in System Settings. This code base has no control over the panel or its support for legacy indicators
