### ISSUE TITLE
[juno beta1] Middle click to paste is not working between different applications

### ISSUE THREAD

**Issue by arshubham** [elementary/switchboard-plug-mouse-touchpad#47]
Middle click to paste is not working between different applications. For example I can select and paste from Firefox to terminal or vice versa. I first thought this may be a Firefox issue but this also doesn't seem to work with the combination of code - Firefox and code - terminal. Although I am able to use the middle click within an application. Therefore if I select something in terminal I can middle click paste it in terminal but not in code.

**Comment by Gabriel-p** [comment]
Is this issue supposed to be fixed now? Because I still get it.

**Comment by gorghino** [comment]
Me too, even if I turned on "Middle click paste"

**Comment by karye** [comment]
Broken my new Juno install too.
Cannot paste from external app to terminal. 
But works from terminal to Chrome for example.

**Comment by Gabriel-p** [comment]
@codygarver why was this issue closed? I still get it on a brand new install I made a week ago.
