### ISSUE TITLE
Right click menu pop up

### ISSUE THREAD

**Issue by dackdel** [elementary/switchboard-plug-mouse-touchpad#53]
The right click menu pop up disappears as soon as it appears. I have to resort to using keyboard shortcuts. Running Juno on a Razer Blade 2017 non-touchscreen laptop.

**Comment by cassidyjames** [comment]
@dackdel is this universal across apps, or confined to certain non-native apps (i.e. Firefox)?

**Comment by dackdel** [comment]
This is only firefox.

**Comment by cassidyjames** [comment]
@dackdel we don't alter any Firefox settings or have control over them. I've head of other users seeing this on various Linux-based OSes, though; it seems you can work around it by heading to [about:config#ui.context_menus.after_mouseup](about:config#ui.context_menus.after_mouseup) and enabling it.

**Comment by heccjj** [comment]
same problem.
I have to change my operating habit, that is right click and don't release until select the menu item i want.
