### ISSUE TITLE
Smooth scrolling support for mouse too, not just touchpad

### ISSUE THREAD

**Issue by sprite-1** [elementary/switchboard-plug-mouse-touchpad#71]
It would really add to the overall experience IMO if the scroll smoothing not only worked on the touchpad, but with the mouse too.

**Comment by Exalm** [comment]
This has nothing to do with the switchboard plug, or even with libinput. It needs to be done in GTK, similar to how it's done in WebKit/Epiphany.

**Comment by sprite-1** [comment]
There's no way to patch it on the elementary side of things?

**Comment by Exalm** [comment]
It's not really relevant. If there's code written, upstreaming it isn't a problem, but there's no code.

**Comment by sprite-1** [comment]
I meant, is there no way for elementary to implement its own smooth scrolling for the system as a whole? I'm not familiar with GTK that's why I'm asking but I don't think it would be impossible

**Comment by Exalm** [comment]
Well, you can have every single elementary app manually implement it. That's possible, though why?

For the system as a whole - no.

**Comment by sprite-1** [comment]
> For the system as a whole - no.

If not true smooth scrolling then can the scroll animation at least be smoothed over then?

**Comment by Exalm** [comment]
That's also GTK job.

**Comment by sprite-1** [comment]
Right, are the GTK team willing to accept PRs if for example, the elementary team added support for it and pushed their changes?

**Comment by Exalm** [comment]
Why not? Also, there isn't a "GTK team", it's also all volunteers.

**Comment by danrabbit** [comment]
I'm going to close this as "Out of Scope" since this is a Gtk issue
