### ISSUE TITLE
Add setting to disable touchpad when external mouse connected

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/switchboard-plug-mouse-touchpad#72]
Mentioned here:
https://www.reddit.com/r/elementaryos/comments/ao5fcz/add_a_feature_on_the_mouse_touchpad_settings/

Happy to implement this if this is a setting that we think should exist.

**Comment by rafaelcn** [comment]
Hello, I'm the author of that reddit post. My hands are here to help if any help is needed :-)
