### ISSUE TITLE
The description labels in the General pane are inconsistent regarding to the use of periods

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-mouse-touchpad#80]
## Actual Behavior

![Screenshot from 2019-04-11 14-29-17](https://user-images.githubusercontent.com/26003928/55933418-2e9e6f00-5c68-11e9-995b-af67d848ea39.png)

The description labels in the General pane are inconsistent regarding to the use of periods: Some of them ends with a period, but others does not.

```
Pressing the control key will highlight the position of the pointer
Long-pressing and releasing the primary button will secondary click.
This disables both levels of keys on the numeric keypad.
Middle or three-finger clicking on an input will paste any selected text
```

## Expected Behavior

The description labels in the General pane should unify the use of periods.

All labels should end with a peroid:

```
Pressing the control key will highlight the position of the pointer.
Long-pressing and releasing the primary button will secondary click.
This disables both levels of keys on the numeric keypad.
Middle or three-finger clicking on an input will paste any selected text.
```

or all labels does not ends with a period:

```
Pressing the control key will highlight the position of the pointer
Long-pressing and releasing the primary button will secondary click
This disables both levels of keys on the numeric keypad
Middle or three-finger clicking on an input will paste any selected text
```

**Comment by cassidyjames** [comment]
From a glance at other plugs like Sound, Display, and Notifications, we more often use periods with this sort of text.

**Comment by cassidyjames** [comment]
To clarify this (and maybe I can propose this to the HIG): single sentences in the UI should likely not use punctuation because it's not necessary. Material Design seems to agree with this: https://material.io/design/communication/writing.html#principles

The exception is with multi-sentence labels or labels that are shown in the same context/alongside multi-sentence labels for consistency.

**Comment by fitojb** [comment]
macOS’ HIG describes it like this: if it’s a sentence fragment, don’t use terminating punctuation; if it is, use it.
