### ISSUE TITLE
Natural scrolling setting inverted for horizontal scrolling

### ISSUE THREAD

**Issue by rockerbacon** [elementary/switchboard-plug-mouse-touchpad#84]
- When natural scrolling is disabled, moving the wheel in one direction scrolls the screen in the opposite direction;
- When natural scrolling is enabled, moving the wheel in one direction scrolls the screen in the same direction;

This is the opposite behaviour of the setting for vertical scrolling.
Tested on multiple applications with a Logitech MX Master 2S.

**Comment by peteruithoven** [comment]
I don't think we can fix this from the mouse settings, this is a per application or gtk issue. Some relevant discussions: https://github.com/elementary/wingpanel-indicator-sound/issues/93
