### ISSUE TITLE
Touchpad Not Working

### ISSUE THREAD

**Issue by sgnd** [elementary/switchboard-plug-mouse-touchpad#85]
My laptop is acer a315-41-r97j

suganda@acer:~$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ E-Signal/A-One USB Gaming Mouse         	id=9	[slave  pointer  (2)]
⎜   ↳ E-Signal/A-One USB Gaming Mouse         	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ VGA WebCam: VGA WebCam                  	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=13	[slave  keyboard (3)]
    ↳ E-Signal/A-One USB Gaming Mouse         	id=14	[slave  keyboard (3)]

How to fix this? Please help me

**Comment by arshubham** [comment]
You might want to give hwe kernel a try. https://blog.elementary.io/updates-for-august-2019/#get-the-hwe-update-today 
Touchpad support is provided by kernel itself 
References for you device: https://bugs.launchpad.net/amd/+bug/1776563
https://community.acer.com/en/discussion/574893/acer-aspire-a315-41-weird-issues-with-touchpad-in-linux

Tip: Search with just "**a315-41**" . **r97j** is just for region specific model.
